# Generated by Django 4.0.5 on 2022-09-25 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Home',
            new_name='Projects',
        ),
    ]
